export const IconButton = <const>{
  EXCEL: 'fa fa-file-excel-o',
  WORD: 'fa fa-file-word-o',
  POWERPOINT: 'fa fa-file-powerpoint-o',
  PDF: 'fa fa-file-pdf-o',
  IMAGE: 'fa fa-file-image-o',
  VIDEO: 'fa fa-file-video-o',
  ADD: 'fa fa-plus',
  EDIT: 'fa fa-pencil-square-o',
  DELETE: 'fa fa-trash-o',
  SEARCH: 'fa fa-search',
  CLEAR: 'fa fa-ban',
  CLOSE: 'fa fa-times',
  RESET: 'fa fa-refresh',
  BACK: 'fa fa-chevron-left',
  SAVE: 'fa fa-check',
  SUBMIT: 'fa fa-check',
  LOCK: 'fa fa-lock',
  CALENDAR: 'fa fa-calendar',
  UPLOAD: 'fa fa-upload',
  CLOUDUPLOAD: 'fa fa-cloud-upload',
  DOWNLOAD: 'fa fa-download',
  CLOUDDOWNLOAD: 'fa fa-cloud-download',
  REMOVE: 'fa fa-remove',
  VIEW: 'fa fa-info',
  UPDATE: 'fa fa-check-square-o',
  BOOKMARK: 'fa fa-bookmark',
  DISABLED: 'fa fa-eye-slash',
  ARROW_RIGHT: 'fa fa-arrow-circle-right',
  AUTHOR: 'fa fa-key',
  COPY: 'fa fa-copy',
  MINUS: 'fa fa-minus',
  ATTACHMENT: 'fa fa-paperclip'
};
export const ClassButton = <const>{
  ADD: 'btn btn-success mr-2',
  SEARCH: 'btn btn-primary mr-2',
  QUERY: 'btn btn-primary mr-2',
  SCAN: 'btn btn-primary mr-2',
  CLEAR: 'btn btn-danger mr-2',
  UPLOAD: 'btn btn-success mr-2',
  DOWNLOAD: 'btn btn-success mr-2',
  EXCEL: 'btn btn-success mr-2',
  PDF: 'btn btn-success mr-2',
  PRINT: 'btn btn-success mr-2',
  SAVE: 'btn btn-success mr-2',
  CLOSE: 'btn btn-danger mr-2',
  CANCEL: 'btn btn-danger mr-2',
  BACK: 'btn btn-primary btn-sm float-right',
  tVIEW: 'btn btn-success btn-sm',
  tDETAIL: 'btn btn-success btn-sm',
  tEDIT: 'btn btn-warning btn-sm',
  tCOPY: 'btn btn-success btn-sm',
  tDELETE: 'btn btn-danger btn-sm',
  tREMOVE: 'btn btn-danger btn-sm',
  tUPDATE: 'btn btn-primary btn-sm',
  tENABLED: 'btn btn-primary btn-sm',
  tDISABLED: 'btn btn-danger btn-sm',
  tDOWNLOAD: 'btn btn-success btn-sm mr-2',
};
export const Placeholder = <const>{
  YearMonthDay: 'YYYY/MM/DD',
  YearMonth: 'YYYY/MM',
  Year: 'YYYY',
  DateTime: 'yyyy/MM/dd HH:mm:ss',
  Email: 'example@email.com'
}
export const EmployeeMode = <const>{
  add: 'add',
  edit: 'edit',
  query: 'query',
  rehire: 'rehire'
}
